# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libdrm

# >> macros
# << macros

Summary:    Direct Rendering Manager runtime library
Version:    2.4.39
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://dri.sourceforge.net
Source0:    http://dri.freedesktop.org/libdrm/%{name}-%{version}.tar.bz2
Source100:  libdrm.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(pciaccess) >= 0.10
BuildRequires:  pkgconfig(pthread-stubs)
BuildRequires:  pkgconfig(udev)

%description
%{summary}


%package omap
Summary:    Direct Rendering Manager omap api
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description omap
%{summary}.


%package radeon
Summary:    Direct Rendering Manager radeon api
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description radeon
%{summary}.


%package nouveau
Summary:    Direct Rendering Manager nouveau api
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description nouveau
%{summary}.


%ifarch %{ix86} x86_64
%package intel
Summary:    Direct Rendering Manager intel api
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description intel
%{summary}.
%endif


%package devel
Summary:    Direct Rendering Manager development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-omap = %{version}-%{release}
Requires:   %{name}-radeon = %{version}-%{release}
Requires:   %{name}-nouveau = %{version}-%{release}
%ifarch %{ix86} x86_64
Requires:   %{name}-intel = %{version}-%{release}
%endif
Requires:   kernel-headers

%description devel
%{summary}.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
unset LD_AS_NEEDED
# >> build pre
# << build pre

%reconfigure --disable-static \
    --enable-omap-experimental-api

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%post omap -p /sbin/ldconfig

%postun omap -p /sbin/ldconfig

%post radeon -p /sbin/ldconfig

%postun radeon -p /sbin/ldconfig

%post nouveau -p /sbin/ldconfig

%postun nouveau -p /sbin/ldconfig

%ifarch %{ix86} x86_64
%post intel -p /sbin/ldconfig

%postun intel -p /sbin/ldconfig

%endif

%files
%defattr(-,root,root,-)
# >> files
%doc README
%{_libdir}/libdrm.so.*
%{_libdir}/libkms.so.*
# << files

%files omap
%defattr(-,root,root,-)
# >> files omap
%{_libdir}/libdrm_omap.so.*
# << files omap

%files radeon
%defattr(-,root,root,-)
# >> files radeon
%{_libdir}/libdrm_radeon.so.*
# << files radeon

%files nouveau
%defattr(-,root,root,-)
# >> files nouveau
%{_libdir}/libdrm_nouveau.so.*
# << files nouveau

%ifarch %{ix86} x86_64
%files intel
%defattr(-,root,root,-)
# >> files intel
%{_libdir}/libdrm_intel.so.*
# << files intel
%endif

%files devel
%defattr(-,root,root,-)
# >> files devel
%dir %{_includedir}/libdrm
%{_includedir}/omap/omap_drm.h
%{_includedir}/libdrm/*.h
%{_includedir}/*.h
%{_libdir}/lib*.so
%{_libdir}/pkgconfig/*.pc
%{_includedir}/libkms/*.h
# << files devel
